name: "Security Issue"
description: "Report a security vulnerability in the project."
title: "[SECURITY] Brief description of the issue"
labels: ["security", "bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a security vulnerability.  
        Please ensure that you provide as much detail as possible to help us address the issue efficiently.

        **Do not disclose the details of this issue publicly until it has been resolved.**
  - type: textarea
    id: vulnerability_description
    attributes:
      label: "Describe the Vulnerability"
      description: "Provide a clear and concise description of the vulnerability."
      placeholder: "What is the issue? How can it be exploited?"
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the vulnerability."
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what should happen if the vulnerability did not exist."
      placeholder: "What should have happened instead?"
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Describe the potential impact of this vulnerability (e.g., data loss, unauthorized access)."
      placeholder: "What is the potential damage caused by this vulnerability?"
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: "Include any other relevant information, such as affected versions or related issues."
      placeholder: "Version numbers, configurations, or related vulnerabilities."
  - type: checkboxes
    id: confidentiality
    attributes:
      label: "Confidentiality Acknowledgment"
      description: "By submitting this report, you agree not to disclose the details of this vulnerability until it has been addressed."
      options:
        - label: "I agree to keep the details of this vulnerability confidential."
          required: true
