CREATE TABLE IF NOT EXISTS `telegram_bots` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL COMMENT 'Descriptive Bot Name',
  `bot_token` VARCHAR(255) NOT NULL COMMENT 'Telegram Bot Token from @BotFather',
  `bot_username` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Cached bot username @username',
  `chat_id` VARCHAR(100) NOT NULL COMMENT 'Target Telegram Channel or Chat ID (@channel or -100...)',
  `chat_title` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Target Channel or Chat Title',
  `content_types` VARCHAR(255) NOT NULL DEFAULT 'movies' COMMENT 'Comma-separated list of content types: movies,episodes,live',
  `categories` TEXT NULL DEFAULT NULL COMMENT 'JSON array of allowed category IDs, or NULL for all',
  `image_type` ENUM('poster', 'backdrop', 'none') NOT NULL DEFAULT 'poster' COMMENT 'Image to attach: poster, backdrop, or none',
  `notify_on_movie_complete` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 = Notify when movie finishes downloading completely',
  `notify_on_episode` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = Notify when series episode is ready',
  `notify_on_live` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = Notify when live stream is created',
  `custom_template` TEXT NULL DEFAULT NULL COMMENT 'Custom caption template (optional)',
  `silent_notification` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = Send silently without sound',
  `include_button` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = Include inline URL button',
  `button_text` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Custom inline button text',
  `button_url` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Custom inline button URL (supports {stream_id})',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 = Active, 0 = Paused/Disabled',
  `total_sent` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Counter of successfully sent messages',
  `last_sent_at` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Timestamp of last sent message',
  `last_error` TEXT NULL DEFAULT NULL COMMENT 'Last error message if failed',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `telegram_logs` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `bot_id` INT UNSIGNED NOT NULL,
  `stream_id` INT UNSIGNED NOT NULL,
  `content_type` ENUM('movie', 'episode', 'live', 'test') NOT NULL,
  `chat_id` VARCHAR(100) NOT NULL,
  `message_id` VARCHAR(100) NULL DEFAULT NULL,
  `status` ENUM('sent', 'failed') NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `details` TEXT NULL DEFAULT NULL,
  `sent_at` DATETIME NOT NULL,
  INDEX `idx_bot_stream` (`bot_id`, `stream_id`, `content_type`),
  INDEX `idx_sent_at` (`sent_at`),
  CONSTRAINT `fk_telegram_logs_bot` FOREIGN KEY (`bot_id`) REFERENCES `telegram_bots` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
