-- ============================================================
-- Migration 023: Seed default stream categories, bouquets & packages
-- ============================================================

SET NAMES utf8mb4;

-- 1. Stream Categories
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (1, 'live', '⚽ BEIN SPORTS | HD & 4K VIP', 0, 1, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (2, 'live', '🏆 SSC SPORTS | SAUDI SPORTS HD', 0, 2, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (3, 'live', '🥊 WORLD SPORTS | Sky, TNT, ESPN, DAZN', 0, 3, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (4, 'live', '👑 VIP | OSN NETWORK PREMIUM', 0, 4, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (5, 'live', '⭐ VIP | SHAHID VIP CHANNELS', 0, 5, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (6, 'live', '🌍 ARABIC | NILESAT GENERAL', 0, 6, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (7, 'live', '🇪🇬 ARABIC | EGYPT PACK', 0, 7, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (8, 'live', '🇸🇦 ARABIC | GULF & SAUDI', 0, 8, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (9, 'live', '🇱🇧 ARABIC | LEBANON & SYRIA', 0, 9, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (10, 'live', '🇲🇦 ARABIC | MAGHREB (Morocco, Algeria, Tunisia)', 0, 10, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (11, 'live', '🎬 ARABIC | CINEMA & MOVIES CHANNELS', 0, 11, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (12, 'live', '🎭 ARABIC | DRAMA & SERIES CHANNELS', 0, 12, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (13, 'live', '👶 KIDS & ANIMATION CHANNELS', 0, 13, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (14, 'live', '🦁 DOCUMENTARY & DISCOVERY CHANNELS', 0, 14, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (15, 'live', '📰 ARABIC & WORLD NEWS CHANNELS', 0, 15, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (16, 'live', '☪️ ISLAMIC & HOLY QURAN CHANNELS', 0, 16, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (17, 'live', '✝️ CHRISTIAN CHANNELS', 0, 17, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (18, 'live', '🎶 ARABIC & WORLD MUSIC', 0, 18, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (19, 'live', '🇬🇧 UNITED KINGDOM (UK) CHANNELS', 0, 19, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (20, 'live', '🇺🇸 UNITED STATES (USA) CHANNELS', 0, 20, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (21, 'live', '🇫🇷 FRANCE CHANNELS', 0, 21, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (22, 'live', '🇩🇪 GERMANY CHANNELS', 0, 22, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (23, 'live', '🇮🇹 ITALY CHANNELS', 0, 23, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (24, 'live', '🇪🇸 SPAIN CHANNELS', 0, 24, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (25, 'live', '🇹🇷 TURKEY CHANNELS', 0, 25, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (26, 'live', '🇮🇳 INDIA & PAKISTAN CHANNELS', 0, 26, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (27, 'live', '🔞 FOR ADULTS ONLY (+18)', 0, 27, 1);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (28, 'movie', '🍿 ARABIC | NEW RELEASES 2025-2026', 0, 1, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (29, 'movie', '🎬 ARABIC | CLASSIC CINEMA', 0, 2, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (30, 'movie', '💥 ARABIC | COMEDY & DRAMA', 0, 3, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (31, 'movie', '🌟 ENGLISH | 4K ULTRA HD MOVIES', 0, 4, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (32, 'movie', '🔥 ENGLISH | ACTION & THRILLER', 0, 5, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (33, 'movie', '🎭 ENGLISH | DRAMA & CRIME', 0, 6, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (34, 'movie', '🚀 ENGLISH | SCI-FI & FANTASY', 0, 7, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (35, 'movie', '😱 ENGLISH | HORROR & SUSPENSE', 0, 8, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (36, 'movie', '😂 ENGLISH | COMEDY & ROMANCE', 0, 9, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (37, 'movie', '👶 KIDS & FAMILY ANIMATION (DUBBED)', 0, 10, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (38, 'movie', '🧸 DISNEY & PIXAR CLASSICS', 0, 11, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (39, 'movie', '🇹🇷 TURKISH MOVIES (SUB & DUB)', 0, 12, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (40, 'movie', '🇮🇳 BOLLYWOOD & INDIAN MOVIES', 0, 13, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (41, 'movie', '🥋 ASIAN & MARTIAL ARTS', 0, 14, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (42, 'movie', '📚 DOCUMENTARIES & BIOGRAPHIES', 0, 15, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (43, 'movie', '🔴 NETFLIX EXCLUSIVE MOVIES', 0, 16, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (44, 'movie', '🔵 PRIME & DISNEY+ ORIGINALS', 0, 17, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (45, 'movie', '🔞 MOVIES FOR ADULTS (+18)', 0, 18, 1);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (46, 'series', '📺 ARABIC | RAMADAN 2025-2026', 0, 1, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (47, 'series', '🌟 ARABIC | SHAHID VIP EXCLUSIVES', 0, 2, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (48, 'series', '🇪🇬 ARABIC | EGYPTIAN SERIES', 0, 3, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (49, 'series', '🇸🇾 ARABIC | SYRIAN & LEBANESE SERIES', 0, 4, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (50, 'series', '🇸🇦 ARABIC | GULF & KHALEENI SERIES', 0, 5, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (51, 'series', '🇲🇦 ARABIC | MAGHREB SERIES', 0, 6, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (52, 'series', '🇹🇷 TURKISH SERIES (ARABIC DUBBED)', 0, 7, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (53, 'series', '🇹🇷 TURKISH SERIES (SUBTITLED)', 0, 8, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (54, 'series', '🔴 NETFLIX TOP SERIES', 0, 9, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (55, 'series', '🖤 HBO & MAX MASTERPIECES', 0, 10, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (56, 'series', '🔵 AMAZON PRIME ORIGINALS', 0, 11, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (57, 'series', '🍏 APPLE TV+ SERIES', 0, 12, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (58, 'series', '💥 ENGLISH | ACTION & CRIME SERIES', 0, 13, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (59, 'series', '🚀 ENGLISH | SCI-FI & FANTASY SERIES', 0, 14, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (60, 'series', '🎭 ENGLISH | DRAMA & MYSTERY', 0, 15, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (61, 'series', '🎎 KOREAN & ASIAN DRAMAS', 0, 16, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (62, 'series', '🎌 ANIME & ANIMATED SERIES (COMPLETE)', 0, 17, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (63, 'series', '👶 KIDS & CARTOON SERIES', 0, 18, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (64, 'series', '🦁 DOCUMENTARY MINISERIES', 0, 19, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (65, 'radio', '📻 HOLY QURAN RADIO (المصحف المرتل ومشاهير القراء)', 0, 1, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (66, 'radio', '📻 ISLAMIC RECITATIONS & LECTURES (محاضرات وابتهالات)', 0, 2, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (67, 'radio', '📻 ARABIC NEWS RADIO (BBC, Monte Carlo, Al Jazeera)', 0, 3, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (68, 'radio', '📻 SPORTS LIVE RADIO (بث المباريات والتحليلات الرياضية)', 0, 4, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (69, 'radio', '📻 ARABIC CLASSICS & TARAB (أم كلثوم، فيروز، عبد الحليم)', 0, 5, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (70, 'radio', '📻 MODERN ARABIC HITS & POP (أحدث الأغاني العربية)', 0, 6, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (71, 'radio', '📻 INTERNATIONAL TOP 40 & POP (الراديو العالمي)', 0, 7, 0);
INSERT IGNORE INTO `streams_categories` (`id`, `category_type`, `category_name`, `parent_id`, `cat_order`, `is_adult`) VALUES (72, 'radio', '📻 CHILLOUT, JAZZ & RELAXATION (موسيقى هادئة واسترخاء)', 0, 8, 0);

-- 2. Bouquets
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (1, '👑 VIP | FULL ALL-IN-ONE (Every Channel & Category)', '[]', '[]', '[]', '[]', 1);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (2, '⚽ SPORTS | WORLD & ARABIC SPORTS VIP', '[]', '[]', '[]', '[]', 2);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (3, '🎬 CINEMA & VOD | MOVIES & SERIES VIP', '[]', '[]', '[]', '[]', 3);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (4, '🌍 ARABIC PACK | NILESAT, ARABSAT & OSN', '[]', '[]', '[]', '[]', 4);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (5, '🇬🇧 UK & 🇺🇸 USA ENTERTAINMENT', '[]', '[]', '[]', '[]', 5);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (6, '🇫🇷 EUROPEAN PACK (FR, DE, IT, ES, TR)', '[]', '[]', '[]', '[]', 6);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (7, '👶 KIDS, FAMILY & DOCUMENTARIES', '[]', '[]', '[]', '[]', 7);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (8, '☪️ ISLAMIC & QURAN PACK', '[]', '[]', '[]', '[]', 8);
INSERT IGNORE INTO `bouquets` (`id`, `bouquet_name`, `bouquet_channels`, `bouquet_movies`, `bouquet_radios`, `bouquet_series`, `bouquet_order`) VALUES (9, '🔞 FOR ADULTS ONLY (18+)', '[]', '[]', '[]', '[]', 9);

-- 3. Users Packages
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (1, '🎯 TRIAL 24H | Free Test (24 Hours)', 0, 1, 0, 0, 0, 24, 'hours', 0, 'months', '[1,2]', '[1,2,3,4,5,6,7,8]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (2, '⚡ VIP PREMIUM | 1 Month Full Access', 0, 0, 1, 0, 1, 0, 'hours', 1, 'months', '[1,2]', '[1,2,3,4,5,6,7,8]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (3, '🌟 VIP PREMIUM | 3 Months Full Access', 0, 0, 1, 0, 3, 0, 'hours', 3, 'months', '[1,2]', '[1,2,3,4,5,6,7,8]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (4, '🔥 VIP PREMIUM | 6 Months Full Access', 0, 0, 1, 0, 6, 0, 'hours', 6, 'months', '[1,2]', '[1,2,3,4,5,6,7,8]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (5, '👑 VIP PREMIUM | 12 Months Full Access', 0, 0, 1, 0, 12, 0, 'hours', 12, 'months', '[1,2]', '[1,2,3,4,5,6,7,8]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (6, '⚽ SPORTS ONLY | 12 Months Access', 0, 0, 1, 0, 10, 0, 'hours', 12, 'months', '[1,2]', '[2]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (7, '🎬 CINEMA & VOD ONLY | 12 Months Access', 0, 0, 1, 0, 10, 0, 'hours', 12, 'months', '[1,2]', '[3,7]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);
INSERT IGNORE INTO `users_packages` (`id`, `package_name`, `is_addon`, `is_trial`, `is_official`, `trial_credits`, `official_credits`, `trial_duration`, `trial_duration_in`, `official_duration`, `official_duration_in`, `groups`, `bouquets`, `addon_packages`, `is_line`, `is_mag`, `is_e2`, `is_restreamer`, `is_isplock`, `output_formats`, `max_connections`, `force_server_id`, `forced_country`, `lock_device`, `check_compatible`) VALUES (8, '🔞 VIP + ADULT PACK | 12 Months Full Access', 0, 0, 1, 0, 14, 0, 'hours', 12, 'months', '[1,2]', '[1,2,3,4,5,6,7,8,9]', '[]', 1, 1, 1, 0, 0, '[1,2,3]', 1, 0, '', 0, 1);

UPDATE `users_packages` SET `bouquets` = '[1,2,3,4,5,6,7,8]' WHERE `id` = 1 AND (`bouquets` = '[]' OR `bouquets` IS NULL);

-- 4. Default Category Template
INSERT IGNORE INTO `category_templates` (`id`, `owner_id`, `name`, `is_system`, `is_shared`, `live_count`, `vod_count`, `series_count`, `radio_count`, `created_at`, `updated_at`) VALUES (13, 1, '⭐ Official Default Layout', 1, 1, 27, 18, 19, 8, '2026-09-12 07:47:21', '2026-09-12 07:47:21');
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (77, 13, 1, 'live', 1, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (78, 13, 2, 'live', 2, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (79, 13, 3, 'live', 3, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (80, 13, 4, 'live', 4, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (81, 13, 5, 'live', 5, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (82, 13, 6, 'live', 6, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (83, 13, 7, 'live', 7, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (84, 13, 8, 'live', 8, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (85, 13, 9, 'live', 9, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (86, 13, 10, 'live', 10, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (87, 13, 11, 'live', 11, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (88, 13, 12, 'live', 12, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (89, 13, 13, 'live', 13, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (90, 13, 14, 'live', 14, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (91, 13, 15, 'live', 15, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (92, 13, 16, 'live', 16, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (93, 13, 17, 'live', 17, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (94, 13, 18, 'live', 18, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (95, 13, 19, 'live', 19, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (96, 13, 20, 'live', 20, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (97, 13, 21, 'live', 21, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (98, 13, 22, 'live', 22, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (99, 13, 23, 'live', 23, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (100, 13, 24, 'live', 24, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (101, 13, 25, 'live', 25, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (102, 13, 26, 'live', 26, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (103, 13, 27, 'live', 27, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (104, 13, 28, 'movie', 1, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (105, 13, 29, 'movie', 2, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (106, 13, 30, 'movie', 3, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (107, 13, 31, 'movie', 4, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (108, 13, 32, 'movie', 5, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (109, 13, 33, 'movie', 6, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (110, 13, 34, 'movie', 7, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (111, 13, 35, 'movie', 8, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (112, 13, 36, 'movie', 9, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (113, 13, 37, 'movie', 10, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (114, 13, 38, 'movie', 11, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (115, 13, 39, 'movie', 12, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (116, 13, 40, 'movie', 13, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (117, 13, 41, 'movie', 14, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (118, 13, 42, 'movie', 15, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (119, 13, 43, 'movie', 16, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (120, 13, 44, 'movie', 17, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (121, 13, 45, 'movie', 18, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (122, 13, 46, 'series', 1, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (123, 13, 47, 'series', 2, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (124, 13, 48, 'series', 3, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (125, 13, 49, 'series', 4, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (126, 13, 50, 'series', 5, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (127, 13, 51, 'series', 6, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (128, 13, 52, 'series', 7, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (129, 13, 53, 'series', 8, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (130, 13, 54, 'series', 9, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (131, 13, 55, 'series', 10, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (132, 13, 56, 'series', 11, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (133, 13, 57, 'series', 12, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (134, 13, 58, 'series', 13, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (135, 13, 59, 'series', 14, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (136, 13, 60, 'series', 15, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (137, 13, 61, 'series', 16, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (138, 13, 62, 'series', 17, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (139, 13, 63, 'series', 18, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (140, 13, 64, 'series', 19, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (141, 13, 65, 'radio', 1, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (142, 13, 66, 'radio', 2, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (143, 13, 67, 'radio', 3, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (144, 13, 68, 'radio', 4, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (145, 13, 69, 'radio', 5, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (146, 13, 70, 'radio', 6, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (147, 13, 71, 'radio', 7, 1, NULL);
INSERT IGNORE INTO `category_template_items` (`id`, `template_id`, `category_id`, `category_type`, `sort_order`, `is_visible`, `custom_name`) VALUES (148, 13, 72, 'radio', 8, 1, NULL);
