<?php

use PHPUnit\Framework\TestCase;
use XcVm\Core\Auth\AuthRepository;
use XcVm\Core\Process\ProcessRunner;

/**
 * An access code's sign-in and image resizer (`/CODE/login`, `/CODE/resize`)
 * are rate-limited per client address. They have no `.php` in their address,
 * so the `.php` location's rule never reached them. Their rule sits in a zone
 * of the panel's own (`panel` in nginx.conf), so a list of thumbnails never
 * holds back the same address's streams and client API requests (zone `one`).
 * The other pages of a code, its static assets and the Ministra portal are not
 * limited by it; the `.php` location keeps its own rule.
 *
 * The burst holds a list page whose every row shows a thumbnail: the images
 * arrive together the first time.
 *
 * The files are generated by AuthRepository::updateCodes() in a process of
 * its own, on a panel home in the temp directory. nginx checks them when
 * XCVM_TEST_NGINX names one (opt-in, as ClusterNginxConfigTest::testRealNginx).
 */
final class AuditDecisionRateLimitAccessCodesTest extends TestCase {
	/** Runs the generator: argv 1 the panel home, 2 the autoloader, 3 the access codes. */
	private const GENERATOR = <<<'PHP'
		define('MAIN_HOME', $argv[1]);
		define('SERVER_ID', 1);
		require $argv[2];
		$db = new class (json_decode($argv[3], true)) {
			public function __construct(private array $rRows) {
			}
			public function query(string $rQuery, mixed ...$rArgs): bool {
				return true;
			}
			public function num_rows(): int {
				return count($this->rRows);
			}
			public function get_rows(): array {
				return $this->rRows;
			}
		};
		\XcVm\Core\Cluster\NodeRpc::useTransport(static fn () => null);
		\XcVm\Core\Auth\AuthRepository::updateCodes();
		PHP;

	/**
	 * A list of 250 rows with every thumbnail asked for at once: more than a
	 * browser asks, which loads the images of the rows near the viewport.
	 */
	private const LIST_ROWS = 250;

	/** code => access-code type; `tv1` is short, so its locations are written with a closing slash. */
	private const CODES = ['adminpanel' => 0, 'resellers1' => 1, 'adminapi01' => 3, 'resellapi1' => 4, 'tv1' => 6, 'activate' => 7, 'webplayer' => 8];

	private string $rHome = '';

	protected function tearDown(): void {
		if ($this->rHome !== '') {
			ProcessRunner::run(['rm', '-rf', '--', $this->rHome]);
		}
	}

	public function testTheTemplateLimitsTheSignInAndTheResizerInThePanelsZone(): void {
		$rTemplate = self::template();
		$rRule = 'limit_req zone=#ZONE# burst=#BURST# nodelay;';

		$this->assertSame(1, substr_count(self::location($rTemplate, '~ /(login|resize)$'), $rRule), 'the sign-in and the resizer');
		$this->assertStringContainsString('location ~ /(login|resize)$ {', self::location($rTemplate, '^~ /#CODE#'), 'inside the code\'s location, under its allow list');
		$this->assertStringNotContainsString('limit_req', self::location($rTemplate, '@fc_#CODE#'), 'the other pages of the code');
		$this->assertSame(1, substr_count(self::location($rTemplate, '~ \.php$'), 'limit_req zone=one burst=#BURST# nodelay;'), 'the .php location keeps its rule');
		$this->assertSame(2, substr_count($rTemplate, 'limit_req'), 'no other limit, and no status of its own: a refused request answers as the .php one does');
		$this->assertStringNotContainsString('limit_req', self::location($rTemplate, '^~ /#CODE#/assets/'), 'static assets are not limited');

		// The panel's zone is keyed per client address as the streams' is, and is not theirs.
		$rNginx = (string) file_get_contents(MAIN_HOME . 'bin/nginx/conf/nginx.conf');
		$this->assertMatchesRegularExpression('/^\s*limit_req_zone \$binary_remote_addr zone=panel:\d+m rate=\d+r\/s;\r?$/m', $rNginx);
		$this->assertMatchesRegularExpression('/^\s*limit_req_zone \$binary_remote_addr zone=one:\d+m rate=\d+r\/s;\r?$/m', $rNginx);
	}

	public function testEveryGeneratedCodeFileLimitsItsSignInAndResizerAtTheTypesBurst(): void {
		foreach ($this->generate(self::template()) as $rCode => $rConf) {
			$rName = strlen($rCode) >= 4 ? $rCode : $rCode . '/';
			$rBurst = AuthRepository::codeLocation(self::CODES[$rCode])[2];

			$this->assertDoesNotMatchRegularExpression('/#[A-Z]+#/', $rConf, $rCode . ': a placeholder is left');
			$this->assertSame(1, substr_count(self::location($rConf, '~ /(login|resize)$'), 'limit_req zone=panel burst=' . $rBurst . ' nodelay;'), $rCode . ': the sign-in and the resizer');
			$this->assertStringContainsString('try_files $uri @fc_' . $rName . ';', self::location($rConf, '~ /(login|resize)$'), $rCode . ': handed to the front controller');
			$this->assertStringNotContainsString('limit_req', self::location($rConf, '@fc_' . $rName), $rCode . ': the other pages');
			$this->assertSame(1, substr_count(self::location($rConf, '~ \.php$'), 'limit_req zone=one burst=' . $rBurst . ' nodelay;'), $rCode . ': the .php location');
			$this->assertSame(2, substr_count($rConf, 'limit_req'), $rCode);
			$this->assertStringNotContainsString('limit_req', self::location($rConf, '^~ /' . $rName . '/assets/'), $rCode . ': static assets are not limited');
		}
	}

	/** An nginx.conf without the panel's zone (one restored by the update's own nginx -t fallback) is still started. */
	public function testWithoutThePanelsZoneTheRuleUsesTheStreamsZone(): void {
		foreach ($this->generate(self::template(), false) as $rCode => $rConf) {
			$this->assertStringNotContainsString('zone=panel', $rConf, $rCode);
			$this->assertSame(1, substr_count(self::location($rConf, '~ /(login|resize)$'), 'limit_req zone=one burst=' . AuthRepository::codeLocation(self::CODES[$rCode])[2] . ' nodelay;'), $rCode);
		}
	}

	public function testATemplateInstalledBeforeTheRuleStillGetsItInEveryCodeFile(): void {
		// An update keeps the installed bin/nginx/conf/codes, the template with it.
		$rInstalled = (string) preg_replace('/^    # The sign-in and the image resizer.*?^    \}\R/ms', '', self::template());
		$this->assertStringNotContainsString('login|resize', $rInstalled, 'the template as it was');
		$this->assertSame(1, substr_count($rInstalled, 'limit_req'), 'the template as it was: the .php location alone');

		foreach ($this->generate($rInstalled) as $rCode => $rConf) {
			$rBurst = AuthRepository::codeLocation(self::CODES[$rCode])[2];

			$this->assertDoesNotMatchRegularExpression('/#[A-Z]+#/', $rConf, $rCode . ': a placeholder is left');
			$this->assertSame(1, substr_count(self::location($rConf, '~ /(login|resize)$'), 'limit_req zone=panel burst=' . $rBurst . ' nodelay;'), $rCode);
			$this->assertSame(2, substr_count($rConf, 'limit_req'), $rCode);
		}
	}

	/** With no enabled code the admin panel is served at the root, from a file nginx accepts. */
	public function testThePanelWithoutACodeGetsAFileWithoutPlaceholders(): void {
		$this->generate(self::template(), true, false);
		$rDefault = (string) file_get_contents($this->rHome . 'bin/nginx/conf/codes/default.conf');

		$this->assertDoesNotMatchRegularExpression('/#[A-Z]+#/', $rDefault);
		$this->assertStringContainsString('fastcgi_param XC_CODE "";', $rDefault);
		$this->assertStringContainsString('limit_req zone=panel burst=500 nodelay;', $rDefault);
	}

	public function testThePanelsBurstHoldsAListPageWithAThumbnailOnEveryRow(): void {
		foreach ([0 => 'admin', 1 => 'reseller'] as $rCodeType => $rPanel) {
			// The page, its table data, one image per row.
			$this->assertGreaterThanOrEqual(2 + self::LIST_ROWS, AuthRepository::codeLocation($rCodeType)[2], $rPanel);
		}
	}

	public function testNginxAcceptsTheGeneratedCodeFiles(): void {
		$rNginx = (string) getenv('XCVM_TEST_NGINX');
		if ($rNginx === '' || !is_executable($rNginx)) {
			$this->markTestSkipped('no nginx (set XCVM_TEST_NGINX)');
		}
		foreach (['with codes' => true, 'without a code' => false] as $rWhich => $rEnabled) {
			$this->tearDown();
			$this->rHome = '';
			$rConf = $this->home() . 'bin/nginx/conf/';
			$this->assertSame(0, ProcessRunner::run(['cp', '-r', MAIN_HOME . 'bin/nginx/conf/.', $rConf]));
			file_put_contents($rConf . 'ports/http.conf', 'listen 25461;');
			file_put_contents($rConf . 'ports/https.conf', 'listen 25463 ssl;');
			// The user directive needs root and the xc_vm user; neither is needed to test the syntax.
			file_put_contents($rConf . 'nginx.conf', (string) preg_replace('/^user xc_vm;\r?$/m', '', (string) file_get_contents($rConf . 'nginx.conf')));
			mkdir($this->rHome . 'bin/nginx/logs');
			$this->generate(self::template(), true, $rEnabled);

			$this->assertSame(0, ProcessRunner::run([$rNginx, '-p', $this->rHome . 'bin/nginx/', '-t', '-q']), $rWhich . ': nginx -t on nginx.conf with the generated files');
		}
	}

	private static function template(): string {
		return (string) file_get_contents(MAIN_HOME . 'bin/nginx/conf/codes/template');
	}

	/** The body of `location $rName { ... }` in $rConf, its nested locations included. */
	private static function location(string $rConf, string $rName): string {
		$rOpen = 'location ' . $rName . ' {';
		$rStart = strpos($rConf, $rOpen);
		self::assertNotFalse($rStart, $rOpen);
		$rFrom = $rStart + strlen($rOpen);
		$rDepth = 1;
		for ($rAt = $rFrom; $rDepth > 0 && $rAt < strlen($rConf); $rAt++) {
			$rDepth += ['{' => 1, '}' => -1][$rConf[$rAt]] ?? 0;
		}
		self::assertSame(0, $rDepth, $rOpen . ' is not closed');
		return substr($rConf, $rFrom, $rAt - 1 - $rFrom);
	}

	/** A panel home of this test's own, down to the directory of the per-code files. */
	private function home(): string {
		if ($this->rHome === '') {
			$this->rHome = sys_get_temp_dir() . '/xcvm-codes-' . bin2hex(random_bytes(6)) . '/';
			mkdir($this->rHome . 'bin/nginx/conf/codes', 0700, true);
		}
		return $this->rHome;
	}

	/**
	 * What AuthRepository::updateCodes() writes for CODES from $rTemplate, on
	 * a home whose nginx.conf declares the panel's zone or not, with the codes
	 * enabled or not.
	 *
	 * @return array<string, string> code => its nginx file (none when disabled)
	 */
	private function generate(string $rTemplate, bool $rPanelZone = true, bool $rEnabled = true): array {
		$rDir = $this->home() . 'bin/nginx/conf/codes/';
		file_put_contents($rDir . 'template', $rTemplate);
		copy(MAIN_HOME . 'bin/nginx/conf/codes/template_ministra', $rDir . 'template_ministra');
		if (!is_file($this->rHome . 'bin/nginx/conf/nginx.conf') || !$rPanelZone) {
			$rNginx = (string) file_get_contents(MAIN_HOME . 'bin/nginx/conf/nginx.conf');
			file_put_contents($this->rHome . 'bin/nginx/conf/nginx.conf', $rPanelZone ? $rNginx : (string) preg_replace('/^.*zone=panel:.*\R/m', '', $rNginx));
		}

		$rRows = [];
		foreach (self::CODES as $rCode => $rCodeType) {
			$rRows[] = ['id' => count($rRows) + 1, 'code' => $rCode, 'type' => $rCodeType, 'enabled' => (int) $rEnabled, 'whitelist' => $rCodeType === 0 ? '["192.0.2.7"]' : '[]'];
		}
		[$rStatus, $rOut] = ProcessRunner::capture([PHP_BINARY, '-r', self::GENERATOR, '--', $this->rHome, MAIN_HOME . 'vendor/autoload.php', (string) json_encode($rRows)]);
		$this->assertSame(0, $rStatus, $rOut);

		$rFiles = [];
		foreach ($rEnabled ? array_keys(self::CODES) : [] as $rCode) {
			$this->assertFileExists($rDir . $rCode . '.conf');
			$rFiles[$rCode] = (string) file_get_contents($rDir . $rCode . '.conf');
		}
		return $rFiles;
	}
}
