-- An activation code's subscription starts when the code is redeemed: until
-- then its line is switched off. A code an administrator generates has
-- purchase cost 0. Codes generated before these two rules get them here.
-- A version rollback switches the waiting lines back on (the down file); a
-- purchase cost does not come back.
--
-- The line of a code nobody redeemed is switched off (redeeming the code
-- switches it on), and with it a line or device paired with it that took its
-- state. A redeemed code's line stays as it is, also one with no expiry.
-- `lines`.`updated` moves with each row written, so cron:cache_engine rewrites
-- the cached line on its next pass.
UPDATE `lines` l
INNER JOIN `activation_codes` c ON c.`subscriber_id` = l.`id`
SET l.`enabled` = 0
WHERE l.`is_activecode` = 1 AND l.`exp_date` IS NULL AND l.`enabled` = 1
  AND c.`activated_at` IS NULL;

UPDATE `lines` d
INNER JOIN `activation_codes` c ON c.`subscriber_id` = d.`pair_id`
SET d.`enabled` = 0
WHERE d.`is_activecode` = 1 AND d.`exp_date` IS NULL AND d.`enabled` = 1
  AND c.`activated_at` IS NULL
  AND NOT EXISTS (SELECT 1 FROM `activation_codes` r WHERE r.`subscriber_id` = d.`id` AND r.`activated_at` IS NOT NULL);

-- A batch a reseller bought left a purchase record (`users_logs`: active_code /
-- generate, naming the batch), written just before its codes. A code nobody
-- redeemed, or one back in stock, with no such record of its owner was
-- generated by an administrator: its purchase cost becomes 0. The records are
-- read once (DISTINCT keeps them a table of their own: the log has no index to
-- look a batch up by). A name is taken at the 100 characters the code's column
-- holds, in that column's character set and collation: a code then looks its
-- record up by owner and name, not among all the records of its owner.
UPDATE `activation_codes` c
SET c.`purchase_cost` = 0
WHERE c.`purchase_cost` > 0
  AND (c.`activated_at` IS NULL OR c.`status` = 1)
  AND NOT EXISTS (
      SELECT 1 FROM (
          SELECT DISTINCT `owner`, `date`, CONVERT(LEFT(JSON_UNQUOTE(JSON_EXTRACT(`deleted_info`, '$.batch_name')), 100) USING utf8) COLLATE utf8_unicode_ci AS `batch_name`
          FROM `users_logs`
          WHERE `type` = 'active_code' AND `action` = 'generate'
      ) p
      WHERE p.`owner` = c.`created_by`
        AND p.`batch_name` = c.`batch_name`
        AND c.`created_at` BETWEEN p.`date` AND p.`date` + 300
  );
